
import "@styles/globals.css";

export const metadata = {
  title: "PokeHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
